# Generated by Django 3.2.7 on 2022-01-13 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('relationship', models.CharField(max_length=15)),
                ('civil_status', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fscap_no', models.CharField(max_length=10)),
                ('last_name', models.CharField(max_length=25)),
                ('first_name', models.CharField(max_length=25)),
                ('middle_name', models.CharField(max_length=25)),
                ('name_ext', models.CharField(max_length=5, null=True)),
                ('barangay', models.CharField(choices=[('0', 'Amunitan'), ('1', 'Batangan'), ('2', 'Baua'), ('3', 'Cabanbanan Norte'), ('4', 'Cabanbanan Sur'), ('5', 'Cabiraoan'), ('6', 'Callao'), ('7', 'Calayan'), ('8', 'Caroan'), ('9', 'Casitan'), ('10', 'Flourishing'), ('11', 'Ipil'), ('12', 'Isca'), ('13', 'Magrafil'), ('14', 'Minanga'), ('15', 'Rebecca'), ('16', 'Paradise'), ('17', 'Pateng'), ('18', 'Progressive'), ('19', 'San Jose'), ('20', 'Santa Clara'), ('21', 'Santa Cruz'), ('22', 'Santa Maria'), ('23', 'Smart'), ('24', 'Tapel')], default=0, max_length=2)),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(max_length=30)),
                ('contact_number', models.BigIntegerField()),
                ('sex', models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1)),
                ('civil_status', models.CharField(max_length=10)),
                ('occupation', models.CharField(max_length=30)),
                ('skills', models.CharField(max_length=1000)),
                ('annual_income', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.CharField(choices=[(0, 'Admin'), (2, 'Municipal Staff'), (2, 'Barangay User'), (3, 'Senior Citizen')], max_length=1, null=True)),
                ('user_status', models.CharField(choices=[(0, 'Pending'), (1, 'Active'), (2, 'Inactive')], default=1, max_length=1)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_members',
            },
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_img', models.ImageField(upload_to='images/')),
                ('member_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.member')),
            ],
        ),
        migrations.CreateModel(
            name='barangay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=25)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
