# Generated by Django 3.2.7 on 2022-01-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='barangay',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fscap_no',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user_role',
        ),
        migrations.AddField(
            model_name='member',
            name='documents',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='member',
            name='img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(default='test1', max_length=10),
        ),
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='test1', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Inactive')], default='0', max_length=1),
        ),
        migrations.DeleteModel(
            name='barangay',
        ),
        migrations.DeleteModel(
            name='profile',
        ),
    ]
