# Generated by Django 4.0.1 on 2022-01-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_member_password_remove_member_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
