# Generated by Django 4.0.1 on 2022-01-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_member_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='annual_income',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='civil_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='contact_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='last_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='middle_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='occupation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='place_of_birth',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('0', 'Male'), ('1', 'Female')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='skills',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='user_status',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Inactive')], default='0', max_length=1, null=True),
        ),
    ]
