# Generated by Django 4.0.1 on 2022-01-17 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_member_annual_income_alter_member_civil_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='civil_status',
            new_name='civilstatus',
        ),
    ]
