# Generated by Django 4.0.1 on 2022-01-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_civil_status_member_civilstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='civilstatus',
            field=models.CharField(choices=[('0', 'Single'), ('1', 'Married'), ('3', 'Widowed')], max_length=1),
        ),
    ]
