# Generated by Django 4.0.1 on 2022-01-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_member_civilstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user_status',
            new_name='userstatus',
        ),
    ]
