# Generated by Django 4.0.1 on 2022-01-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_user_status_member_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='userstatus',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Inactive')], default='1', max_length=1, null=True),
        ),
    ]
