# Generated by Django 4.0.1 on 2022-01-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_member_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name_ext',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='userstatus',
            field=models.CharField(choices=[('0', 'Pending'), ('1', 'Active'), ('2', 'Inactive'), ('3', 'Archived')], default='1', max_length=1, null=True),
        ),
    ]
