# Generated by Django 4.0.1 on 2022-01-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_member_name_ext_alter_member_userstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='name_ext',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
