# Generated by Django 4.0.1 on 2022-01-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_member_name_ext'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
